maintainer       "Gourav Shah, Initcron"
maintainer_email "gs@initcron.org"
license          "All rights reserved"
description      "Installs/Configures  Hadoop, Zookeeper, Habase, Oozie, Kafka etc."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "2.0.1"
depends          "java"
depends          "runit"
depends          "aws"
depends          "cloudy_s3"
depends          "zookeeper"
#depends          "xfs"
recipe           "hadoop::default", "Installs hadoop base libraries and conguration."
recipe           "hadoop::hbasemaster", "Installs Hbase Master"
recipe           "hadoop::jobtracker", "Installs the JobTracker package and prepares the file system."
recipe           "hadoop::namenode", "Installs the NameNode package and prepares the file system."
recipe           "hadoop::secondarynamenode", "Installs the SecondaryNameNode package and prepares the file system."
recipe           "hadoop::slave", "Installs the DataNode and TaskTracker packages."
recipe           "hadoop:kafka", "Installs kafka."

